# Generated by Django 3.2.4 on 2021-12-20 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title_en', models.CharField(max_length=50, null=True)),
                ('title_az', models.CharField(max_length=50, null=True)),
                ('about_paragraph1', models.TextField(blank=True, max_length=10000, null=True)),
                ('about_paragraph1_en', models.TextField(blank=True, max_length=10000, null=True)),
                ('about_paragraph1_az', models.TextField(blank=True, max_length=10000, null=True)),
                ('about_paragraph2', models.TextField(blank=True, max_length=10000, null=True)),
                ('about_paragraph2_en', models.TextField(blank=True, max_length=10000, null=True)),
                ('about_paragraph2_az', models.TextField(blank=True, max_length=10000, null=True)),
                ('about_paragraph4', models.TextField(blank=True, max_length=10000, null=True)),
                ('about_paragraph4_en', models.TextField(blank=True, max_length=10000, null=True)),
                ('about_paragraph4_az', models.TextField(blank=True, max_length=10000, null=True)),
                ('about_img', models.ImageField(upload_to='media/about')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Haqqımızdada',
            },
        ),
        migrations.CreateModel(
            name='About_service_names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xidmet_ad', models.TextField(blank=True, max_length=1000, null=True)),
                ('xidmet_ad_en', models.TextField(blank=True, max_length=1000, null=True)),
                ('xidmet_ad_az', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'About_service_names',
                'verbose_name_plural': 'Haqqimizda_xidmet_adlari',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(default='Nizami rayonu Əlişir Nəvai küç. 11', max_length=1000)),
                ('phone', models.CharField(default='(+994 12) 574-00-04', max_length=20)),
                ('email', models.EmailField(blank=True, default='office@beteko.az', max_length=254)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Ünvan',
            },
        ),
        migrations.CreateModel(
            name='Approach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title_en', models.CharField(max_length=50, null=True)),
                ('title_az', models.CharField(max_length=50, null=True)),
                ('our_approach_paragraph1', models.TextField(blank=True, max_length=10000, null=True)),
                ('our_approach_paragraph1_en', models.TextField(blank=True, max_length=10000, null=True)),
                ('our_approach_paragraph1_az', models.TextField(blank=True, max_length=10000, null=True)),
                ('our_approach_paragraph2', models.TextField(blank=True, max_length=10000, null=True)),
                ('our_approach_paragraph2_en', models.TextField(blank=True, max_length=10000, null=True)),
                ('our_approach_paragraph2_az', models.TextField(blank=True, max_length=10000, null=True)),
                ('our_approach_paragraph3', models.TextField(blank=True, max_length=10000, null=True)),
                ('our_approach_paragraph3_en', models.TextField(blank=True, max_length=10000, null=True)),
                ('our_approach_paragraph3_az', models.TextField(blank=True, max_length=10000, null=True)),
                ('our_approach_paragraph4', models.TextField(blank=True, max_length=10000, null=True)),
                ('our_approach_paragraph4_en', models.TextField(blank=True, max_length=10000, null=True)),
                ('our_approach_paragraph4_az', models.TextField(blank=True, max_length=10000, null=True)),
                ('our_approach_img', models.ImageField(upload_to='media/our_approach')),
            ],
            options={
                'verbose_name': 'Approach',
                'verbose_name_plural': 'Bizim yanaşmamız',
            },
        ),
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title_en', models.CharField(max_length=50, null=True)),
                ('title_az', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('description_en', models.TextField(max_length=1000, null=True)),
                ('description_az', models.TextField(max_length=1000, null=True)),
                ('image', models.ImageField(upload_to='blog_image')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Careers',
                'verbose_name_plural': 'İs',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=60)),
                ('subject', models.CharField(max_length=1000)),
                ('message', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Əlaqə',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('is_avtive', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Abunəçi',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carusel_image')),
                ('about', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_image', to='core.about')),
                ('approach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approach_image', to='core.approach')),
            ],
            options={
                'verbose_name': 'Images',
                'verbose_name_plural': 'Əsas Şəkil',
            },
        ),
    ]
