# Generated by Django 3.2.4 on 2021-11-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_address_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='location',
            field=models.TextField(default='Nizami rayonu Əlişir Nəvai küç. 11', max_length=1000),
        ),
    ]
