# Generated by Django 3.2.4 on 2021-12-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pdfile_careers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfile',
            name='careers',
        ),
        migrations.AddField(
            model_name='careers',
            name='pdfile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pdfile'),
        ),
    ]
