# Generated by Django 3.2.4 on 2021-12-20 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211220_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careers',
            name='pdfile',
        ),
        migrations.AddField(
            model_name='pdfile',
            name='careers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='careers_required', to='core.careers'),
        ),
    ]
