# Generated by Django 3.2.4 on 2021-12-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_employees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careers',
            options={'verbose_name': 'Careers', 'verbose_name_plural': 'İs Elanlari'},
        ),
    ]
