# Generated by Django 3.2.4 on 2021-10-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_az',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_az',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
