# Generated by Django 3.2.4 on 2021-12-21 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20211220_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryservice',
            old_name='title',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='categoryservice',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='categoryservice',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='categoryservice',
            name='title_en',
        ),
        migrations.CreateModel(
            name='ServiceSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_subcategories', to='services.categoryservice')),
            ],
        ),
    ]
