# Generated by Django 3.2.4 on 2021-12-21 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20211221_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='subcategories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_category', to='services.servicesubcategory'),
        ),
    ]
