# Generated by Django 3.2.4 on 2021-12-21 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='subcategories',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_category', to='services.service'),
        ),
    ]
