# Generated by Django 3.2.4 on 2021-12-21 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryservice',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_subcategories', to='services.categoryservice'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_category', to='services.categoryservice'),
        ),
        migrations.DeleteModel(
            name='ServiceSubCategory',
        ),
    ]
