# Generated by Django 3.2.4 on 2021-12-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20211221_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryservice',
            name='category_az',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='categoryservice',
            name='category_en',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
